{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.backend.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    version: {{ .Values.backend.image.tag }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
      release: {{ .Release.Name }}
      version: {{ .Values.backend.image.tag }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        release: {{ .Release.Name }}
        version: {{ .Values.backend.image.tag }}
      annotations:
        # Enable Istio DNS Proxying so ServiceEntry hostnames are resolvable via Envoy
        proxy.istio.io/config: |
          proxyMetadata:
            ISTIO_META_DNS_CAPTURE: "true"
            ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }}
          name: http
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        {{- if .Values.sealedSecret.enabled }}
        - secretRef:
            name: {{ .Release.Name }}-sealed-secret
        {{- else }}
        - secretRef:
            name: {{ .Release.Name }}-secret
        {{- end }}
        env:
        - name: PYTHONPATH
          value: {{ .Values.backend.env.PYTHONPATH | quote }}
        - name: DB_SCHEMA
          value: {{ .Values.global.namespace | quote }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        {{- if .Values.backend.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.livenessProbe.path }}
            port: {{ .Values.backend.service.targetPort }}
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
        {{- end }}
        {{- if .Values.backend.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.readinessProbe.path }}
            port: {{ .Values.backend.service.targetPort }}
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
        {{- end }}
{{- end }}
