# Secret содержит пароли для app_dev, app_staging, app_prod
# В реальном окружении заменить на SealedSecret или External Secrets Operator
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-users
  namespace: {{ .Values.global.namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- range .Values.schemas }}
  password-{{ .name }}: {{ .password | b64enc | quote }}
  {{- end }}
