apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  annotations:
    # No Istio sidecar injection for database namespace
    sidecar.istio.io/inject: "false"
  labels:
    name: {{ .Values.global.namespace }}
    istio-injection: disabled
