apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: voting-system
  labels:
    app: cockroachdb
spec:
  type: ClusterIP  # unaccessible from outside the cluster
  selector:
    app: cockroachdb
  ports:
  - port: 26257
    targetPort: 26257
    name: grpc # cockroachdb gRPC follow the documentation
  - port: 8080
    targetPort: 8080
    name: http
