apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
data:
  # Python
  PYTHONPATH: {{ .Values.backend.env.PYTHONPATH | quote }}
  
  # Database
  DB_HOST: {{ .Values.configMap.DB_HOST | quote }}
  DB_PORT: {{ .Values.configMap.DB_PORT | quote }}
  DB_USER: {{ .Values.configMap.DB_USER | quote }}
  DB_NAME: {{ .Values.configMap.DB_NAME | quote }}
  
  # Frontend
  NODE_ENV: {{ .Values.frontend.env.NODE_ENV | quote }}
  NEXT_PUBLIC_API_URL: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL | quote }}
  
  # CockroachDB
  COCKROACH_DATABASE: {{ .Values.configMap.COCKROACH_DATABASE | quote }}
