{{- if .Values.database.externalService.enabled }}
# ExternalName Service - приложение обращается к "database",
# а реально попадает на CockroachDB в namespace database
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: {{ .Values.global.namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: ExternalName
  externalName: {{ .Values.database.externalService.host }}
  ports:
  - name: tcp-postgresql
    port: {{ .Values.database.externalService.port }}
    targetPort: {{ .Values.database.externalService.port }}
    protocol: TCP
{{- end }}
