{{- if .Values.sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-sealed-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  encryptedData:
    SECRET_KEY: {{ .Values.sealedSecret.encryptedSecretKey | quote }}
  template:
    metadata:
      name: {{ .Release.Name }}-secret
      namespace: {{ .Values.global.namespace }}
      labels:
        app: {{ .Release.Name }}
{{- end }}
