{{- if not .Values.sealedSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | quote }}
  DB_USER: {{ .Values.secret.DB_USER | quote }}
{{- end }}
