{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  hosts:
    {{- range .Values.istio.hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - mesh
  http:
    - name: backend-routes
      match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: {{ .Values.backend.name }}.{{ .Values.global.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.backend.service.port }}
    - name: frontend-routes
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .Values.frontend.name }}.{{ .Values.global.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}
