"""add_surveys_with_integer_user_id

Revision ID: be1e04b8791c
Revises: 4f9ac3f2eb08
Create Date: 2025-11-10 00:17:08.930572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1e04b8791c'
down_revision: Union[str, Sequence[str], None] = '4f9ac3f2eb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responses_count', sa.Integer(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_surveys_created_by', 'surveys', ['created_by'], unique=False)
    op.create_index('ix_surveys_end_date', 'surveys', ['end_date'], unique=False)
    op.create_index('ix_surveys_status', 'surveys', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('allow_multiple_answers', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_survey_id', 'questions', ['survey_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('option_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_options_question_id', 'question_options', ['question_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['question_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'user_id', 'option_id', name='uq_answers_question_user_option')
    )
    op.create_index('ix_answers_option_id', 'answers', ['option_id'], unique=False)
    op.create_index('ix_answers_question_id', 'answers', ['question_id'], unique=False)
    op.create_index('ix_answers_user_id', 'answers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Calculates y-intercept of the least-squares-fit linear equation determined by the (X, Y) pairs.',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint('ix_users_username', 'users', ['username'])
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_id', 'users', [sa.text('id NULLS FIRST')], unique=False, postgresql_using='prefix')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('ix_users_email', 'users', ['email'])
    op.drop_index('ix_answers_user_id', table_name='answers')
    op.drop_index('ix_answers_question_id', table_name='answers')
    op.drop_index('ix_answers_option_id', table_name='answers')
    op.drop_table('answers')
    op.drop_index('ix_question_options_question_id', table_name='question_options')
    op.drop_table('question_options')
    op.drop_index('ix_questions_survey_id', table_name='questions')
    op.drop_table('questions')
    op.drop_index('ix_surveys_status', table_name='surveys')
    op.drop_index('ix_surveys_end_date', table_name='surveys')
    op.drop_index('ix_surveys_created_by', table_name='surveys')
    op.drop_table('surveys')
    # ### end Alembic commands ###
